# Site settings
title: Siddharth Bhalla
name: Siddharth Bhalla <br/> siddharthbhalla98@gmail.com

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/bhalla98
 - title: LinkedIn
   url: https://www.linkedin.com/in/siddharth-bhalla-829853144/
 - title: Angel.Co
   url: https://angel.co/siddharth-bhalla?public_profile=1

#Any buzzword skills you want to include
skills:
 - Xcode
 - Swift
 - Java
 - C++
 - MATLAB
 - UIKit
 - Core Animation
 - SpeechKit
 - NSLinguistic Tagger
 - AVFoundation


#Work experience is required
roles:
 - title: LinguisticTagger
   description: 	Analyzes and segments natural language text into paragraphs, sentences, words and tags information such as part of speech, lexical class, lemma, script, and language using NSLinguistic Tagger library.
 - title: SpeechRecognitionToText	
   description: Recognizes the user's speech and then converts it into text and displays it using Speech Kit,launched in WWDC 2016. It first gets the access of the device's microphone and then enables the user to input the data through speech and then converts it into text format.
 - title: PitchPerfect
   description: Uses AVFoundation to record user’s voice input using the device’s microphone. It then allows users to play the recorded sound back with six different Sound Modulations:Chipmunk, Darth Vader, Slow, Fast with Reverb and Echo effect.
 - title: MagicalGrid
   description: Swipe and Zoom animation on grids using UIKit, Core Animation and Core Graphics.
 - title: RefME-DTU (Current)	
   description: iOS App allows DTU students to download reference study material, question papers, exam related documents. Navigates students within campus using Google Maps API.

#Education is required
education:
 - level: Bachelor of Technology (B.Tech)
   date: 2016-2020
   subject: Engineering Physics
   school: Delhi Technological University (Formerly DCE)

#List of interesting Github repo/projects to include - optional
github:
 - bhalla98/LinguisticTagger
 - bhalla98/SiriDemo
 - bhalla98/PitchPerfect
 - bhalla98/MagicalGrid
 - bhalla98/Animation-UIKit
 - bhalla98/BlackJack-UI

